name: CI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Download toolchain
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: prereq.yml
          name: toolchain-openssl
          path: toolchain

      - name: Download Qt
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: prereq.yml
          name: qt
          path: qt

      - name: get toolchain and Qt ready
        run: |
          mv toolchain ~/x-tools
          mv qt ~/qt-bin
          chmod -R 777 ~/x-tools
          chmod -R 777 ~/qt-bin

      - name: build
        run: |
          export QTDIR=qt-everywhere-src-5.15.1
          export PATH=~/x-tools/arm-kobo-linux-gnueabihf/bin:$PATH
          export PATH=~/qt-bin/qt-linux-5.15.1-kobo/bin:$PATH
          export SYSROOT=~/x-tools/arm-kobo-linux-gnueabihf/arm-kobo-linux-gnueabihf/sysroot
          cd .. && git clone https://github.com/Rain92/qt5-kobo-platform-plugin
          cd qt5-kobo-platform-plugin
          qmake && make -j5
          cd $GITHUB_WORKSPACE
          qmake CONFIG+=kobo && make -j5

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: UltimateMangaReader
          path: UltimateMangaReader

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: UltimateMangaReader
